#!/bin/sh

_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

# Start after
# * pillow
# * acxmgrd
# * cmd
# * lab126
# * framework

DAEMON=/mnt/us/scripts/weatherscript.sh
NAME=weatherscript
DAEMONUSER=root
DESC="Weather Display Daemon"
CONF_NAME=weatherscript

start_it_up()
{

  echo -n "Starting $DESC: "
  "sleep 60 && /mnt/us/scripts/weatherscript.sh"
}

shut_it_down()
{
  echo -n "Cannot stop $DESC: "
  return
}

case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  restart|force-reload)
    shut_it_down
    sleep 1
    start_it_up
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
